// components/basic/fuzzy-image/FuzzyImage.vue
<template>
  <div
    v-if="img"
    class="fuzzy-image"
    :class="{ 'fuzzy-image-background': background }"
    ref="imgContainer"
    :data-image-full="img"
  >
    <img ref="image" :src="minImg" />
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref, computed } from "vue";

export default defineComponent({
  name: "FuzzyImage",
  props: {
    img: {
      type: String,
      default: "",
      required: true,
    },
    minImg: {
      type: String,
      default: "",
      required: true,
    },
    background: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const imgContainer = ref<HTMLDivElement>();
    const image = ref<HTMLImageElement>();

    const minImgBackground = computed<string>(() => `url(${props.minImg})`);

    const setNewImage = (imageUrl: string | null): void => {
      if (imgContainer.value && imageUrl) {
        imgContainer.value.style.backgroundImage = `url(${imageUrl})`;
        imgContainer.value.classList.add("fuzzy-image-loaded");
      }
    };

    const lazyLoad = (): void => {
      if (imgContainer.value) {
        const imageUrl: string | null =
          imgContainer.value.getAttribute("data-image-full");

        if (image.value) {
          image.value.src = imageUrl || "";

          image.value.addEventListener("load", () => setNewImage(imageUrl));
        }
      }
    };

    onMounted(lazyLoad);

    return {
      image,
      imgContainer,
      minImgBackground,
      lazyLoad,
      setNewImage,
    };
  },
});
</script>

<style lang="scss" scoped>
.fuzzy-image {
  background-size: cover;
  filter: blur(5px);
  background-image: v-bind(minImgBackground);

  &-background {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    z-index: -1;
    background-position: center;
  }

  & > img {
    display: block;
    height: 100%;
    width: 100%;
    opacity: 0;
  }

  &-loaded {
    filter: none;
    transition: filter 3s;
  }
}
</style>

// src/components/FuzzyImage/FuzzyImage.tsx
import React, { useRef, useState } from "react";

// Styles
import "./FuzzyImage.scss";

interface Props {
  img: string;
  minImg: string;
  background?: boolean;
}

const FuzzyImage = ({ img, minImg, background }: Props) => {
  // ** Data **
  const imgContainer = useRef<HTMLDivElement>(null);
  const image = useRef<HTMLImageElement>(null);

  // ** Methods **
  const setNewImage = (imageUrl: string | null): void => {
    if (imgContainer?.current && imageUrl) {
      imgContainer.current.style.backgroundImage = img;
      imgContainer.current.classList.add("fuzzy-image-loaded");
    }
  };

  const lazyLoad = (): void => {
    if (imgContainer?.current) {
      const imageUrl: string | null =
        imgContainer.current.getAttribute("data-image-full");

      if (image?.current) {
        image.current.src = imageUrl || "";

        image.current.addEventListener("load", () => setNewImage(imageUrl));
      }
    }
  };

  useState(() => setTimeout(lazyLoad, 100));

  return (
    <div
      className={`fuzzy-image ${background ? "fuzzy-image-background" : ""}`}
      ref={imgContainer}
      style={{ "--minImg": minImg } as React.CSSProperties}
      data-image-full={img}
    >
      <img ref={image} src={minImg} alt="" />
    </div>
  );
};

export default FuzzyImage;
