// src/footer/Footer.vue
<template>
  <footer class="grey darken-4 white--text py-4" id="footer">
    <div class="footer-content max-width ">
      <div class="contact-links" v-if="windowWidth < 768">
        <span
          class="d-flex justify-center align-center mobile-icon"
          style="cursor: default"
        >
          <v-icon color="white" class="mr-2" small aria-label="mobile phone"
            >fas fa-phone-alt</v-icon
          >
          07414 095408
        </span>
        <v-hover>
          <span
            slot-scope="{ hover }"
            style="cursor: pointer"
            class="d-flex justify-center align-center"
            :class="hover ? 'primary-lighter--text' : ''"
            @click="sendEmail"
          >
            <v-icon
              class="mr-2"
              :color="hover ? 'primary-lighter' : 'white'"
              small
              aria-label="email"
              >fas fa-envelope</v-icon
            >contact@buildadream.co.uk
          </span>
        </v-hover>
      </div>
      <div :class="windowWidth < 768 ? 'text-center' : ''">
        <p class="my-0">&copy; 2021 Build A-Dream. All Rights Reserved.</p>
        <p class="my-0">
          Site created by
          <a class="white--text" href="https://alex-long.co.uk/" target="_blank"
            >Alex</a
          >
        </p>
      </div>
      <div class="contact-links" v-if="windowWidth >= 768">
        <span class="d-flex align-center mobile-icon" style="cursor: default">
          <v-icon color="white" class="mr-2" aria-label="mobile phone" small
            >fas fa-phone-alt</v-icon
          >
          07414 095408
        </span>
        <v-hover>
          <span
            slot-scope="{ hover }"
            style="cursor: pointer"
            class="d-flex align-center"
            :class="hover ? 'primary-lighter--text' : ''"
            @click="sendEmail"
          >
            <v-icon
              class="mr-2"
              :color="hover ? 'primary-lighter' : 'white'"
              small
              aria-label="email"
              >fas fa-envelope</v-icon
            >contact@buildadream.co.uk
          </span>
        </v-hover>
      </div>
    </div>
  </footer>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class Footer extends Vue {
  @Prop()
  windowWidth!: number;

  sendEmail(): void {
    window.location.href = "mailto:contact@builda-dream.com";
  }
}
</script>
<style lang="scss">
#footer {
  box-shadow: 4px -5px 6px 0px #00000015;
  border-top: 1px solid #e5e5e5;
  .footer-content {
    width: 90%;
  }
  .contact-links {
    text-align: center;
    margin-bottom: 10px;
  }
  @media (min-width: 768px) {
    .footer-content {
      display: flex;
      justify-content: space-between;
    }
  }
}
</style>

// src/compounds/Footer.svelte
<footer class="bg-dark-grey text-white py-6 w-full text-left border-t border-white 1024px:py-10">
    <div class="w-3/4 mx-auto 1024px:max-w-48rem 1440px:max-w-62rem">
        <div class="1024px:flex justify-between 1024px:mb-12">
            <div class="text-center mb-6 1024px:mb-0">
                <a class="hover:text-primary" href="/">Home</a>
                |
                <a class="hover:text-primary" href="/work">Our Work</a>
                |
                <a class="hover:text-primary" href="/contact">Contact Us</a>
            </div>
            <div class="1024px:flex">
                <a class="flex items-center mb-2 1024px:mb-0 1024px:mr-4 hover:text-primary" href="tel:07414095408"><img class="w-4 mr-2" src="/icons/phone.svg" alt=""> 07414 095408</a>
                <a class="flex items-center hover:text-primary" href="mailto:contact@builda-dream.com"><img class="w-4 mr-2" src="/icons/mail.svg" alt=""> contact@builda-dream.com</a>
            </div>
        </div>
        <div class="py-2 1024px:flex justify-between">
            <p class="mt-4 1024px:m-0">&copy; 2020 Build A-Dream Lincoln Landscape Gardeners</p>
            <p class="mt-2 1024px:m-0">Site created by <a class="text-primary" href="https://alex-long.co.uk/">Alex</a></p>
        </div>
    </div>
</footer>
