// src/compounds/Footer.svelte
<footer class="bg-dark-grey text-white py-6 w-full text-left border-t border-white 1024px:py-10">
    <div class="w-3/4 mx-auto 1024px:max-w-48rem 1440px:max-w-62rem">
        <div class="1024px:flex justify-between 1024px:mb-12">
            <div class="text-center mb-6 1024px:mb-0">
                <a class="hover:text-primary" href="/">Home</a>
                |
                <a class="hover:text-primary" href="/work">Our Work</a>
                |
                <a class="hover:text-primary" href="/contact">Contact Us</a>
            </div>
            <div class="1024px:flex">
                <a class="flex items-center mb-2 1024px:mb-0 1024px:mr-4 hover:text-primary" href="tel:07414095408"><img class="w-4 mr-2" src="/icons/phone.svg" alt=""> 07414 095408</a>
                <a class="flex items-center hover:text-primary" href="mailto:contact@builda-dream.com"><img class="w-4 mr-2" src="/icons/mail.svg" alt=""> contact@builda-dream.com</a>
            </div>
        </div>
        <div class="py-2 1024px:flex justify-between">
            <p class="mt-4 1024px:m-0">&copy; 2020 Build A-Dream Lincoln Landscape Gardeners</p>
            <p class="mt-2 1024px:m-0">Site created by <a class="text-primary" href="https://alex-long.co.uk/">Alex</a></p>
        </div>
    </div>
</footer>

// components/footer/Footer.vue
<template>
  <footer class="bd-footer xf-pt-8">
    <div class="bd-navigation-max-width">
      <div class="xf-flex-center">
        <div class="xf-text-14">
          <h4 class="xf-mb-2">Contact</h4>

          <a class="bd-footer-link" :href="`mailto:${content.email}`">
            <XfIcon
              class="xf-mr-2"
              :src="getDynamicAsset('icons/mail.svg')"
              :size="14"
            />
            {{ content.email }}
          </a>

          <div>
            <XfIcon
              class="xf-mr-1"
              :src="getDynamicAsset('icons/phone.svg')"
              :size="14"
            />
            {{ content.phone }}
          </div>

          <div>
            <XfIcon
              class="xf-mr-1"
              :src="getDynamicAsset('icons/location.svg')"
              :size="14"
            />
            {{ content.location }}
          </div>
        </div>

        <div class="xf-ml-10">
          <h4 class="xf-mb-2">Pages</h4>

          <ul>
            <li
              v-for="(route, i) in content.routes"
              :key="i"
              class="xf-text-14"
            >
              <nuxt-link :to="route.route">
                {{ route.text }}
              </nuxt-link>
            </li>
          </ul>
        </div>
      </div>

      <p class="xf-text-center xf-text-12 xf-mt-8 xf-pb-4">
        &copy; {{ currentYear }} Build A-Dream Landscape Gardeners
      </p>
    </div>
  </footer>
</template>

<script lang="ts" setup>
import { XfIcon } from "xf-cmpt-lib";
import content from "~/content/navigation.json";

// ** Data **
const currentYear: number = new Date().getFullYear();
</script>

<style lang="scss" scoped>
.bd-footer {
  background: white;

  &-link {
    display: flex;
    align-items: center;
  }

  &-border-right {
    border-right: 1px solid grey;
  }
}
</style>
